version: '2'
services:
    frontend:
        build: images/apache
        image: onyx/frontend
        container_name: onyx-frontend
        volumes:
            - ..:/var/www/onyx
        ports:
            - "${WEB_PORT}:80"
        environment:
            - USER_ID=${USER_ID}
            - GROUP_ID=${GROUP_ID}
